---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set default UFW policies
  ufw:
    rule: default
    policy: deny
    direction: incoming

- name: Allow outgoing traffic
  ufw:
    rule: default
    policy: allow
    direction: outgoing

- name: Allow SSH
  ufw:
    rule: allow
    port: 22/tcp

- name: Allow HTTP
  ufw:
    rule: allow
    port: 80/tcp

- name: Allow HTTPS
  ufw:
    rule: allow
    port: 443/tcp

- name: Enable UFW
  ufw:
    state: enabled
